// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALVObI53SMldEUrYBrsQ5bJ_SUJj_PBvc',
    appId: '1:677535983657:web:dfa78d79bff5904df1d438',
    messagingSenderId: '677535983657',
    projectId: 'wasteagram-8fc4d',
    authDomain: 'wasteagram-8fc4d.firebaseapp.com',
    storageBucket: 'wasteagram-8fc4d.appspot.com',
    measurementId: 'G-HEFKQK6B9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD32LR_MXYkf8M0NjmYa8waMUIiMjGGLSw',
    appId: '1:677535983657:android:b6e0d119421a155ef1d438',
    messagingSenderId: '677535983657',
    projectId: 'wasteagram-8fc4d',
    storageBucket: 'wasteagram-8fc4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGTEQHOczqww6lC_fsazq86AjhB3b4GdY',
    appId: '1:677535983657:ios:476d3142d0e0d19bf1d438',
    messagingSenderId: '677535983657',
    projectId: 'wasteagram-8fc4d',
    storageBucket: 'wasteagram-8fc4d.appspot.com',
    iosClientId: '677535983657-n9rf4ikq8v7ek6mgvri7m7lamsvpu7b5.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.reynollu.wasteagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGTEQHOczqww6lC_fsazq86AjhB3b4GdY',
    appId: '1:677535983657:ios:94a469a7cabbcf1df1d438',
    messagingSenderId: '677535983657',
    projectId: 'wasteagram-8fc4d',
    storageBucket: 'wasteagram-8fc4d.appspot.com',
    iosClientId: '677535983657-nhne8i0ep6hgdois16hnk61s04vneral.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.reynollu.wasteagram.RunnerTests',
  );
}
